version: "3.9"

services:
  web:
    container_name: web
    build: ./web
    restart: always
    ports:
      - 80:8000
    links:
      - db:mariadb
  
  db:
    container_name: maria
    image: mariadb:10.5
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    restart: always
    environment: 
      MARIADB_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    volumes:
      - ./web/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - db-storage:/var/lib/mysql

volumes:
  db-storage: